In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/raw/indicators_mdg.csv")
pd.options.display.float_format = '{:,.2f}'.format
df.head(3)

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
0,Madagascar,MDG,2023,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,7.28
1,Madagascar,MDG,2022,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,6.88
2,Madagascar,MDG,2021,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,6.53

In [3]:
df = df.rename(columns={'Country Name':'country_name', 'Country ISO3':'country_iso', 'Year':'year', 'Indicator Name':'indicator_name', 'Indicator Code':'indicator_code', 'Value':'value'})
df.sample(5)

,country_name,country_iso,year,indicator_name,indicator_code,value
12126,Madagascar,MDG,2008,Adjusted savings: education expenditure (% of ...,NY.ADJ.AEDU.GN.ZS,2.64
43599,Madagascar,MDG,1991,"Population ages 0-14, female (% of female popu...",SP.POP.0014.FE.ZS,45.48
28887,Madagascar,MDG,1971,Population ages 0-14 (% of total population),SP.POP.0014.TO.ZS,46.38
68609,Madagascar,MDG,1989,Short-term debt (% of total external debt),DT.DOD.DSTC.ZS,3.60
61142,Madagascar,MDG,1998,Population in the largest city (% of urban pop...,EN.URB.LCTY.UR.ZS,33.89

In [4]:
df.shape

(76129, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76129 entries, 0 to 76128
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    76129 non-null  object
 1   country_iso     76129 non-null  object
 2   year            76129 non-null  int64
 3   indicator_name  76129 non-null  object
 4   indicator_code  76129 non-null  object
 5   value           76129 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 3.5+ MB

In [6]:
df.isnull().sum()

country_name      0
country_iso       0
year              0
indicator_name    0
indicator_code    0
value             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(18502)

In [8]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [9]:
df['indicator_name'].describe()

count                                            57627
unique                                            2709
top       Domestic credit to private sector (% of GDP)
freq                                               122
Name: indicator_name, dtype: object

In [10]:
df['year'].describe().astype(int)

count    57627
mean      1999
std         15
min       1960
25%       1990
50%       2003
75%       2012
max       2025
Name: year, dtype: int64

In [11]:
df['value'] = df['value'].apply(
    lambda x: np.float64(x).round(2)
)
df.sample(10)

,country_name,country_iso,year,indicator_name,indicator_code,value
3116,Madagascar,MDG,2012,"Net official flows from UN agencies, UNFPA (cu...",DT.NFL.UNFP.CD,"3,564,394.95"
68986,Madagascar,MDG,2024,"Net financial flows, multilateral (NFL, curren...",DT.NFL.MLAT.CD,"391,177,000.00"
12402,Madagascar,MDG,2004,Adjusted savings: consumption of fixed capital...,NY.ADJ.DKAP.GN.ZS,7.54
35207,Madagascar,MDG,2014,People using safely managed drinking water ser...,SH.H2O.SMDW.RU.ZS,8.70
54736,Madagascar,MDG,1995,"Bound rate, simple mean, primary products (%)",TM.TAX.TCOM.BR.ZS,29.83
46703,Madagascar,MDG,1989,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,0.45
7580,Madagascar,MDG,1978,General government final consumption expenditu...,NE.CON.GOVT.ZS,11.89
9262,Madagascar,MDG,1985,Exports of goods and services (annual % growth),NE.EXP.GNFS.KD.ZG,0.79
42616,Madagascar,MDG,1981,"Mortality rate, adult, male (per 1,000 male ad...",SP.DYN.AMRT.MA,384.72
14192,Madagascar,MDG,1989,GDP per capita (current US$),NY.GDP.PCAP.CD,271.31

In [12]:
df.groupby('indicator_name')['value'].describe()

,count,mean,std,min,25%,50%,75%,max
indicator_name,,,,,,,,
Total fertility rate (TFR) (births per woman): Q1 (lowest),7.00,6.69,0.79,5.50,6.40,6.70,6.85,8.10
Total fertility rate (TFR) (births per woman): Q2,7.00,5.70,0.75,4.80,5.00,5.90,6.35,6.50
Total fertility rate (TFR) (births per woman): Q3,7.00,5.23,0.88,4.30,4.55,5.10,5.65,6.80
Total fertility rate (TFR) (births per woman): Q4,7.00,4.33,0.84,3.30,3.70,4.40,4.75,5.70
Total fertility rate (TFR) (births per woman): Q5 (highest),7.00,2.94,0.27,2.70,2.75,2.80,3.10,3.40
...,...,...,...,...,...,...,...,...
Young people (ages 15-24) newly infected with HIV,35.00,702.57,621.10,100.00,200.00,570.00,920.00,"2,700.00"
"Youth illiterate population, 15-24 years, % female",5.00,52.27,1.18,51.37,51.44,51.44,53.46,53.66
"Youth illiterate population, 15-24 years, both sexes (number)",5.00,"1,173,507.80","261,460.07","910,466.00","1,017,012.00","1,033,814.00","1,409,082.00","1,497,165.00"
"Youth illiterate population, 15-24 years, female (number)",5.00,"611,651.20","126,535.74","488,569.00","523,144.00","552,659.00","724,861.00","769,023.00"
"Youth illiterate population, 15-24 years, male (number)",5.00,"561,856.80","135,414.27","421,897.00","481,155.00","493,868.00","684,221.00","728,143.00"

In [13]:
df['theme_code'] = df['indicator_code'].apply(
    lambda x: str(x).split('.')[0].split('_')[0].upper()
)
df.sample(5)

,country_name,country_iso,year,indicator_name,indicator_code,value,theme_code
41817,Madagascar,MDG,2006,"Tuberculosis case detection rate (%, all forms)",SH.TBS.DTEC.ZS,47.00,SH
57467,Madagascar,MDG,2011,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.WR.ZS,5.95,TX
50703,Madagascar,MDG,2006,ICT goods exports (% of total goods exports),TX.VAL.ICTG.ZS.UN,0.30,TX
35225,Madagascar,MDG,2021,People using safely managed drinking water ser...,SH.H2O.SMDW.UR.ZS,36.60,SH
59588,Madagascar,MDG,1965,Military expenditure (current LCU),MS.MIL.XPND.CN,"528,800,000.00",MS

In [14]:
df.groupby('theme_code')['value'].describe()

,count,mean,std,min,25%,50%,75%,max
theme_code,,,,,,,,
AG,"1,100.00","491,914.46","942,227.56",0.01,21.45,144.48,"581,540.00","5,389,921.52"
BG,51.00,15.13,6.22,4.64,9.93,15.93,20.03,26.92
BM,692.00,"504,981,593.75","1,131,642,069.57","-8,476,000.00",28.12,"18,023,625.61","431,540,870.60","6,523,065,010.12"
BN,559.00,"-152,135,112.03","422,054,797.72","-2,093,613,078.08","-265,865,212.15","-54,477,792.97","2,228,836.65","2,470,175,866.11"
BX,"1,017.00","305,587,811.51","722,029,859.93","-6,581,395.81",21.14,"12,184,519.95","315,436,493.41","4,738,122,495.76"
DC,"1,077.00","27,533,988.01","75,500,809.71","-620,000.00","209,999.99","2,000,000.00","16,100,000.38","813,520,019.58"
DT,"2,847.00","268,200,774.13","764,063,412.82","-91,104,102.00",14.95,"3,339,999.91","96,268,373.10","6,653,640,488.30"
EE,6.00,"97,908.56","19,426.45","66,857.92","89,857.80","98,211.29","113,196.65","118,905.80"
EG,769.00,"980,639.25","12,789,417.75","-51,420,000.00",1.70,14.80,67.30,"290,630,000.00"
EN,"2,354.00","146,841.42","723,421.37",-19.55,0.04,0.69,15.46,"7,731,000.00"
ER,631.00,"24,165.96","43,665.03",0.00,3.97,96.98,"29,570.40","189,950.94"
FB,124.00,29.82,69.23,0.27,2.70,7.95,20.69,466.59
FD,82.00,15.46,6.65,6.66,11.64,14.08,16.62,36.21
FI,231.00,"283,544,726.44","583,169,359.00",0.06,3.88,"29,225,634.72","225,453,920.76","2,784,591,092.62"
FM,656.00,"648,791,599,076.05","2,459,427,660,694.21","-581,282,226,502.74",6.84,14.80,"8,858,000,000.00","21,723,480,473,264.80"
FP,123.00,35.11,59.81,-1.70,4.35,9.25,30.62,280.82
FR,174.00,28.31,16.61,-9.58,13.25,25.57,43.34,60.00
FS,126.00,8.51,6.04,-6.47,4.80,9.05,13.64,18.62
FX,29.00,23.11,9.98,5.52,16.68,21.51,26.78,48.97
GB,18.00,0.12,0.07,0.01,0.09,0.12,0.17,0.29
GC,"1,011.00","451,241,697,516.91","1,157,659,949,417.83","-3,221,958,412,234.73",8.23,41.17,"345,145,056,489.33","9,730,674,821,124.85"
GF,11.00,83.44,17.51,60.60,70.03,81.35,95.31,118.49
GFDD,"1,450.00",88.24,324.53,0.00,4.50,13.64,40.97,"3,075.93"
HD,36.00,0.39,0.02,0.34,0.37,0.39,0.40,0.42
IC,141.00,"3,776.07","8,390.24",0.00,14.32,52.56,"1,429.00","43,666.00"
IE,19.00,"45,333,684.21","70,791,919.75","5,000,000.00","17,800,000.00","21,750,000.00","29,720,000.00","245,100,000.00"
IP,163.00,544.76,980.91,1.00,14.00,60.66,297.50,"3,686.00"
IQ,519.00,10.69,19.12,1.10,3.00,3.50,4.00,90.00
IS,266.00,"96,790.58","177,342.26",1.00,15.93,883.00,"94,555.30","657,953.00"
IT,526.00,"20,013,122,317.79","100,459,390,600.65",0.00,0.27,11.43,"31,543.00","1,040,000,000,000.00"
LO,18.00,39.54,23.79,6.20,25.80,36.40,52.45,81.40
LP,54.00,2.40,0.55,1.00,2.15,2.33,2.65,5.00
MS,307.00,"17,719,599,749.65","66,105,753,791.08",0.00,1.50,"22,000.00","71,933,841.25","552,020,000,000.00"
NE,"3,760.00","1,989,214,210,618.94","6,647,877,167,818.68","-10,287,185,603,359.30",18.88,"1,132,427,668.30","114,889,831,300.00","99,162,500,082,700.00"
NV,"1,097.00","1,342,479,137,217.33","3,870,758,216,112.27",-22.76,18.83,"2,492.64","25,939,005,200.00","43,393,957,372,537.70"
NY,"4,737.00","1,732,902,140,223.83","7,103,472,142,810.20","-2,319,174,375,600.00",4.31,"16,799.55","9,616,879,409.44","88,875,314,198,800.00"
PA,204.00,986.98,"1,166.91",42.26,92.57,511.92,"1,317.70","4,529.75"
PER,431.00,15.66,20.89,-0.49,1.03,7.51,20.58,99.18
SE,"3,602.00","79,055.99","423,509.89",0.00,8.55,33.28,79.70,"5,349,010.00"
SG,207.00,27.72,28.99,0.00,3.92,17.20,43.33,93.70
SH,"4,994.00","2,893.38","10,589.12",0.00,7.60,29.20,73.59,"164,000.00"
SI,143.00,37.53,28.46,1.90,13.20,32.50,56.80,98.60
SL,"2,306.00","394,698.74","1,773,751.84",0.00,12.75,68.83,85.07,"17,092,352.00"
SM,82.00,283.93,"10,147.30","-18,345.00","-2,679.75","-1,893.50",-290.50,"38,625.00"
SN,101.00,56.08,47.75,3.00,27.50,39.50,76.70,250.00
SP,"12,447.00","904,117.65","2,127,324.58",0.20,16.91,"210,508.00","1,043,403.00","32,740,678.00"
ST,216.00,"145,157,350.89","195,026,472.29",2.61,"108,025.00","91,500,000.00","164,000,000.00","951,000,000.00"
TG,66.00,32.17,10.82,13.87,24.92,28.73,41.66,59.18
TM,"1,919.00","103,395,258.65","514,867,488.45",-0.00,2.92,11.43,39.24,"5,471,000,000.00"
TT,20.00,87.62,4.92,80.10,84.47,85.90,89.33,100.00
TX,"1,498.00","89,441,902.20","376,800,507.74",-0.00,1.62,6.65,60.86,"3,609,000,000.00"
UIS,"2,592.00","91,952.42","265,544.70",0.03,15.00,54.38,"51,850.75","4,155,445.00"
VC,18.00,"86,050.00","97,375.62","1,300.00","20,250.00","44,500.00","109,500.00","291,000.00"

In [15]:
df.isnull().sum()

country_name      0
country_iso       0
year              0
indicator_name    0
indicator_code    0
value             0
theme_code        0
dtype: int64

In [ ]:
map_prefixes = {
    # Demographics & Social
    "SP": "Demographics & Population",
    "SH": "Health & Nutrition",
    "SE": "Education (WDI)",
    "UIS": "Education (UNESCO)",
    "SL": "Labor & Employment",
    "PER": "Social Protection & Poverty",
    "HD": "Human Development",
    "SG": "Gender Statistics",
    "SM": "Social Cohesion",
    "SN": "Social Safety Nets",
    # Economy & Finance
    "NY": "GDP & National Accounts",
    "NE": "Expenditure & Investment",
    "NV": "Sectoral Value Added",
    "DT": "External Debt",
    "FM": "Money & Financial Markets",
    "FR": "Foreign Reserves",
    "FI": "Financial Institutions",
    "FD": "Financial Development",
    "FS": "Banking Structure",
    "FX": "Exchange Rates",
    "DC": "Domestic Credit",
    "GFDD": "Financial Development (GFDD)",
    # Trade & Public Finance
    "BX": "Exports (Balance of Payments)",
    "BM": "Imports (Balance of Payments)",
    "BN": "Net Balance of Payments",
    "GC": "Central Government Finance",
    "GF": "General Government Finance",
    "TX": "Merchandise Exports",
    "TM": "Merchandise Imports",
    "TT": "Terms of Trade",
    "TG": "Goods Trade",
    "BG": "Development Aid (ODA)",
    "VC": "Global Value Chains",
    # Environment & Infrastructure
    "AG": "Agriculture & Food",
    "EN": "Environment & Climate",
    "ER": "Natural Resources",
    "EG": "Energy & Power",
    "EE": "Energy Efficiency",
    "IT": "Telecom & Digital",
    "IP": "Intellectual Property",
    "IS": "Industry Statistics",
    "FP": "Food Prices",
    "ST": "Tourism",
    # Governance & Private Sector
    "IC": "Investment Climate",
    "IQ": "Institutional Quality",
    "PA": "Public Administration",
    "MS": "Mining & Services",
    "LP": "Labor Productivity",
    "LO": "Labor Governance",
    "FB": "Financial Behavior",
    "IE": "International Integration",
}

# Mapping direct
df["theme"] = df["theme_code"].map(map_prefixes).fillna("Other / Specific")
d

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57627 entries, 0 to 70220
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    57627 non-null  object
 1   country_iso     57627 non-null  object
 2   year            57627 non-null  int64
 3   indicator_name  57627 non-null  object
 4   indicator_code  57627 non-null  object
 5   value           57627 non-null  float64
 6   theme_code      57627 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 3.5+ MB

In [18]:
df.to_csv('../data/processed/indicator_mdg_cleaned.csv', index=False)