In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/raw/indicators_mdg.csv")
df.head(3)

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
0,Madagascar,MDG,2023,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,7.283000
1,Madagascar,MDG,2022,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,6.877333
2,Madagascar,MDG,2021,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,6.525667

In [3]:
df = df.rename(columns={'Country Name':'country_name', 'Country ISO3':'country_iso', 'Year':'year', 'Indicator Name':'indicator_name', 'Indicator Code':'indicator_code', 'Value':'value'})
df.sample(5)

,country_name,country_iso,year,indicator_name,indicator_code,value
74400,Madagascar,MDG,2011,Import value index (2015 = 100),TM.VAL.MRCH.XD.WD,1.040000e+02
65727,Madagascar,MDG,1980,"Age population, age 03, female",SP.POP.AG03.FE.IN,1.616550e+05
56114,Madagascar,MDG,2018,Commercial service imports (current US$),TM.VAL.SERV.CD.WT,1.123374e+09
14447,Madagascar,MDG,1997,GDP per capita (constant LCU),NY.GDP.PCAP.KN,7.488750e+05
42122,Madagascar,MDG,2008,Domestic general government health expenditure...,SH.XPD.GHED.PC.CD,7.229201e+00

In [4]:
df.shape

(76129, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76129 entries, 0 to 76128
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    76129 non-null  object
 1   country_iso     76129 non-null  object
 2   year            76129 non-null  int64
 3   indicator_name  76129 non-null  object
 4   indicator_code  76129 non-null  object
 5   value           76129 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 3.5+ MB

In [6]:
df.isnull().sum()

country_name      0
country_iso       0
year              0
indicator_name    0
indicator_code    0
value             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(18502)

In [8]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [9]:
df['indicator_name'].describe()

count                                            57627
unique                                            2709
top       Domestic credit to private sector (% of GDP)
freq                                               122
Name: indicator_name, dtype: object

In [10]:
df['year'].describe().astype(int)

count    57627
mean      1999
std         15
min       1960
25%       1990
50%       2003
75%       2012
max       2025
Name: year, dtype: int64

In [11]:
df['value'] = df['value'].apply(
    lambda x: np.float64(x).round(2)
)
df.sample(10)

,country_name,country_iso,year,indicator_name,indicator_code,value
27092,Madagascar,MDG,1972,"Adjusted net enrollment rate, primary, male (%...",SE.PRM.TENR.MA,7.123000e+01
40707,Madagascar,MDG,1988,"Immunization, DPT (% of children ages 12-23 mo...",SH.IMM.IDPT,4.200000e+01
43453,Madagascar,MDG,2005,"Population ages 00-04, male (% of male populat...",SP.POP.0004.MA.5Y,1.737000e+01
4517,Madagascar,MDG,2002,"Charges for the use of intellectual property, ...",BM.GSR.ROYL.CD,2.290136e+07
58418,Madagascar,MDG,2023,Tax revenue (current LCU),GC.TAX.TOTL.CN,6.758983e+12
56134,Madagascar,MDG,1998,Commercial service imports (current US$),TM.VAL.SERV.CD.WT,3.262672e+08
26870,Madagascar,MDG,2002,"Repeaters, primary, female (% of female enroll...",SE.PRM.REPT.FE.ZS,2.942000e+01
61093,Madagascar,MDG,1981,Population in largest city,EN.URB.LCTY,6.092090e+05
39226,Madagascar,MDG,2008,"Banking crisis dummy (1=banking crisis, 0=none)",GFDD.OI.19,0.000000e+00
25752,Madagascar,MDG,2011,"School enrollment, secondary (gross), gender p...",SE.ENR.SECO.FM.ZS,9.500000e-01

In [12]:
df.groupby('indicator_name')['value'].describe()

,count,mean,std,min,25%,50%,75%,max
indicator_name,,,,,,,,
Total fertility rate (TFR) (births per woman): Q1 (lowest),7.0,6.685714e+00,0.786190,5.50,6.40,6.70,6.85,8.10
Total fertility rate (TFR) (births per woman): Q2,7.0,5.700000e+00,0.746101,4.80,5.00,5.90,6.35,6.50
Total fertility rate (TFR) (births per woman): Q3,7.0,5.228571e+00,0.882637,4.30,4.55,5.10,5.65,6.80
Total fertility rate (TFR) (births per woman): Q4,7.0,4.328571e+00,0.840068,3.30,3.70,4.40,4.75,5.70
Total fertility rate (TFR) (births per woman): Q5 (highest),7.0,2.942857e+00,0.269921,2.70,2.75,2.80,3.10,3.40
...,...,...,...,...,...,...,...,...
Young people (ages 15-24) newly infected with HIV,35.0,7.025714e+02,621.101218,100.00,200.00,570.00,920.00,2700.00
"Youth illiterate population, 15-24 years, % female",5.0,5.227400e+01,1.176427,51.37,51.44,51.44,53.46,53.66
"Youth illiterate population, 15-24 years, both sexes (number)",5.0,1.173508e+06,261460.067955,910466.00,1017012.00,1033814.00,1409082.00,1497165.00
"Youth illiterate population, 15-24 years, female (number)",5.0,6.116512e+05,126535.740327,488569.00,523144.00,552659.00,724861.00,769023.00
"Youth illiterate population, 15-24 years, male (number)",5.0,5.618568e+05,135414.272528,421897.00,481155.00,493868.00,684221.00,728143.00

In [13]:
df['theme_code'] = df['indicator_code'].apply(
    lambda x: str(x).split('.')[0].split('_')[0].upper()
)
df.sample(5)

,country_name,country_iso,year,indicator_name,indicator_code,value,theme_code
11930,Madagascar,MDG,2019,"Services, value added (constant 2015 US$)",NV.SRV.TOTL.KD,6.476013e+09,NV
31511,Madagascar,MDG,1995,Total greenhouse gas emissions excluding LULUC...,EN.GHG.ALL.PC.CE.AR5,1.720000e+00,EN
23704,Madagascar,MDG,1996,"Repeaters in Grade 2 of primary education, bot...",UIS.R.1.G2,1.139660e+05,UIS
58041,Madagascar,MDG,2004,Grants and other revenue (current LCU),GC.REV.GOTR.CN,7.696490e+11,GC
59446,Madagascar,MDG,2012,Armed forces personnel (% of total labor force),MS.MIL.TOTL.TF.ZS,1.900000e-01,MS

In [14]:
df.groupby('theme_code')['value'].describe()

,count,mean,std,min,25%,50%,75%,max
theme_code,,,,,,,,
AG,1100.0,4.919145e+05,9.422276e+05,1.000000e-02,2.145250e+01,1.444800e+02,5.815400e+05,5.389922e+06
BG,51.0,1.512765e+01,6.215523e+00,4.640000e+00,9.930000e+00,1.593000e+01,2.003000e+01,2.692000e+01
BM,692.0,5.049816e+08,1.131642e+09,-8.476000e+06,2.812250e+01,1.802363e+07,4.315409e+08,6.523065e+09
BN,559.0,-1.521351e+08,4.220548e+08,-2.093613e+09,-2.658652e+08,-5.447779e+07,2.228837e+06,2.470176e+09
BX,1017.0,3.055878e+08,7.220299e+08,-6.581396e+06,2.114000e+01,1.218452e+07,3.154365e+08,4.738122e+09
DC,1077.0,2.753399e+07,7.550081e+07,-6.200000e+05,2.100000e+05,2.000000e+06,1.610000e+07,8.135200e+08
DT,2847.0,2.682008e+08,7.640634e+08,-9.110410e+07,1.495000e+01,3.340000e+06,9.626837e+07,6.653640e+09
EE,6.0,9.790856e+04,1.942645e+04,6.685792e+04,8.985780e+04,9.821129e+04,1.131966e+05,1.189058e+05
EG,769.0,9.806392e+05,1.278942e+07,-5.142000e+07,1.700000e+00,1.480000e+01,6.730000e+01,2.906300e+08
EN,2354.0,1.468414e+05,7.234214e+05,-1.955000e+01,4.000000e-02,6.850000e-01,1.545500e+01,7.731000e+06
ER,631.0,2.416596e+04,4.366503e+04,0.000000e+00,3.970000e+00,9.698000e+01,2.957040e+04,1.899509e+05
FB,124.0,2.982161e+01,6.922718e+01,2.700000e-01,2.702500e+00,7.950000e+00,2.069250e+01,4.665900e+02
FD,82.0,1.546159e+01,6.650599e+00,6.660000e+00,1.164500e+01,1.408000e+01,1.661500e+01,3.621000e+01
FI,231.0,2.835447e+08,5.831694e+08,6.000000e-02,3.885000e+00,2.922563e+07,2.254539e+08,2.784591e+09
FM,656.0,6.487916e+11,2.459428e+12,-5.812822e+11,6.837500e+00,1.480500e+01,8.858000e+09,2.172348e+13
FP,123.0,3.511106e+01,5.980812e+01,-1.700000e+00,4.345000e+00,9.250000e+00,3.062000e+01,2.808200e+02
FR,174.0,2.830609e+01,1.661009e+01,-9.580000e+00,1.325000e+01,2.557500e+01,4.334000e+01,6.000000e+01
FS,126.0,8.506984e+00,6.044752e+00,-6.470000e+00,4.800000e+00,9.050000e+00,1.363750e+01,1.862000e+01
FX,29.0,2.310517e+01,9.979796e+00,5.520000e+00,1.668000e+01,2.151000e+01,2.678000e+01,4.897000e+01
GB,18.0,1.216667e-01,7.245688e-02,1.000000e-02,9.000000e-02,1.200000e-01,1.725000e-01,2.900000e-01
GC,1011.0,4.512417e+11,1.157660e+12,-3.221958e+12,8.235000e+00,4.117000e+01,3.451451e+11,9.730675e+12
GF,11.0,8.344182e+01,1.750554e+01,6.060000e+01,7.002500e+01,8.135000e+01,9.531000e+01,1.184900e+02
GFDD,1450.0,8.823627e+01,3.245287e+02,0.000000e+00,4.502500e+00,1.364000e+01,4.096750e+01,3.075930e+03
HD,36.0,3.850000e-01,1.963961e-02,3.400000e-01,3.700000e-01,3.900000e-01,4.000000e-01,4.200000e-01
IC,141.0,3.776070e+03,8.390235e+03,0.000000e+00,1.432000e+01,5.256000e+01,1.429000e+03,4.366600e+04
IE,19.0,4.533368e+07,7.079192e+07,5.000000e+06,1.780000e+07,2.175000e+07,2.972000e+07,2.451000e+08
IP,163.0,5.447634e+02,9.809109e+02,1.000000e+00,1.400000e+01,6.066000e+01,2.975000e+02,3.686000e+03
IQ,519.0,1.068798e+01,1.911984e+01,1.100000e+00,3.000000e+00,3.500000e+00,4.000000e+00,9.000000e+01
IS,266.0,9.679058e+04,1.773423e+05,1.000000e+00,1.592500e+01,8.830000e+02,9.455530e+04,6.579530e+05
IT,526.0,2.001312e+10,1.004594e+11,0.000000e+00,2.700000e-01,1.143000e+01,3.154300e+04,1.040000e+12
LO,18.0,3.953889e+01,2.378705e+01,6.200000e+00,2.580000e+01,3.640000e+01,5.245000e+01,8.140000e+01
LP,54.0,2.395000e+00,5.539455e-01,1.000000e+00,2.152500e+00,2.330000e+00,2.652500e+00,5.000000e+00
MS,307.0,1.771960e+10,6.610575e+10,0.000000e+00,1.505000e+00,2.200000e+04,7.193384e+07,5.520200e+11
NE,3760.0,1.989214e+12,6.647877e+12,-1.028719e+13,1.887500e+01,1.132428e+09,1.148898e+11,9.916250e+13
NV,1097.0,1.342479e+12,3.870758e+12,-2.276000e+01,1.883000e+01,2.492640e+03,2.593901e+10,4.339396e+13
NY,4737.0,1.732902e+12,7.103472e+12,-2.319174e+12,4.310000e+00,1.679955e+04,9.616879e+09,8.887531e+13
PA,204.0,9.869772e+02,1.166908e+03,4.226000e+01,9.257250e+01,5.119200e+02,1.317700e+03,4.529750e+03
PER,431.0,1.566283e+01,2.088996e+01,-4.900000e-01,1.030000e+00,7.510000e+00,2.057500e+01,9.918000e+01
SE,3602.0,7.905599e+04,4.235099e+05,0.000000e+00,8.547500e+00,3.328500e+01,7.969750e+01,5.349010e+06
SG,207.0,2.771696e+01,2.898579e+01,0.000000e+00,3.925000e+00,1.720000e+01,4.332500e+01,9.370000e+01
SH,4994.0,2.893383e+03,1.058912e+04,0.000000e+00,7.600000e+00,2.919500e+01,7.359500e+01,1.640000e+05
SI,143.0,3.753371e+01,2.846354e+01,1.900000e+00,1.320000e+01,3.250000e+01,5.680000e+01,9.860000e+01
SL,2306.0,3.946987e+05,1.773752e+06,0.000000e+00,1.275000e+01,6.883000e+01,8.507250e+01,1.709235e+07
SM,82.0,2.839268e+02,1.014730e+04,-1.834500e+04,-2.679750e+03,-1.893500e+03,-2.905000e+02,3.862500e+04
SN,101.0,5.608020e+01,4.774571e+01,3.000000e+00,2.750000e+01,3.950000e+01,7.670000e+01,2.500000e+02
SP,12447.0,9.041177e+05,2.127325e+06,2.000000e-01,1.690500e+01,2.105080e+05,1.043403e+06,3.274068e+07
ST,216.0,1.451574e+08,1.950265e+08,2.610000e+00,1.080250e+05,9.150000e+07,1.640000e+08,9.510000e+08
TG,66.0,3.216758e+01,1.081780e+01,1.387000e+01,2.492000e+01,2.872500e+01,4.166500e+01,5.918000e+01
TM,1919.0,1.033953e+08,5.148675e+08,-0.000000e+00,2.915000e+00,1.143000e+01,3.924000e+01,5.471000e+09
TT,20.0,8.762000e+01,4.915989e+00,8.010000e+01,8.447500e+01,8.590000e+01,8.932500e+01,1.000000e+02
TX,1498.0,8.944190e+07,3.768005e+08,-0.000000e+00,1.620000e+00,6.650000e+00,6.085750e+01,3.609000e+09
UIS,2592.0,9.195242e+04,2.655447e+05,3.000000e-02,1.500000e+01,5.437500e+01,5.185075e+04,4.155445e+06
VC,18.0,8.605000e+04,9.737562e+04,1.300000e+03,2.025000e+04,4.450000e+04,1.095000e+05,2.910000e+05

In [15]:
df.isnull().sum()

country_name      0
country_iso       0
year              0
indicator_name    0
indicator_code    0
value             0
theme_code        0
dtype: int64

In [20]:
df.sample(7)

,country_name,country_iso,year,indicator_name,indicator_code,value,theme_code
539,Madagascar,MDG,1994,Forest area (sq. km),AG.LND.FRST.K2,1.342834e+05,AG
1989,Madagascar,MDG,1982,"Net bilateral aid flows from DAC donors, Canad...",DC.DAC.CANL.CD,2.810000e+06,DC
9455,Madagascar,MDG,1989,"Gross fixed capital formation, private sector ...",NE.GDI.FPRV.CN,3.882000e+11,NE
68305,Madagascar,MDG,2011,"External debt stocks, long-term (DOD, current ...",DT.DOD.DLXF.CD,2.163632e+09,DT
58298,Madagascar,MDG,2003,Customs and other import duties (% of tax reve...,GC.TAX.IMPT.ZS,5.050000e+01,GC
7807,Madagascar,MDG,1985,Households and NPISHs Final consumption expend...,NE.CON.PRVT.KD,4.686078e+09,NE
42079,Madagascar,MDG,2003,Domestic general government health expenditure...,SH.XPD.GHED.GD.ZS,2.170000e+00,SH

In [16]:
df.to_csv('../data/processed/indicator_mdg_cleaned.csv', index=False)